### ISSUE TITLE
[Problem of dataset] Training data for chess rules and raw data for comments

### ISSUE THREAD

**Issue by Inch-Z** [waterhorse1/ChessGPT#2]
Hello, I am very interested in this work and will pay attention to the data set you released. However, unfortunately, I have not seen your description and use of the data set on hugging face or github. At the same time, I am also curious about your training plan and raw data content rather than processed tfrecords data, and I look forward to your reply.
I hope you can improve the README document or open source checkpoint for us to evaluate. Thank you very much.

**Comment by waterhorse1** [comment]
Hi,

Thanks for your interest in our work. Since our dataset includes a lot of datasets, we cannot detail every dataset description in huggingface. You can refer to our paper for that. And About raw data content, what do you mean by saying tfrecords? I don't think our dataset consists of any tfrecord datasets. About the open-source checkpoint, do you mean the checkpoint during our training process, or just the last checkpoint?

**Comment by Inch-Z** [comment]
I hope to get your last checkpoint. If you are willing to open source all checkpoints, I will be grateful.

**Comment by waterhorse1** [comment]
I think we do open the last checkpoint of the model, https://huggingface.co/Waterhorse/chessgpt-base-v1, or do I miss anything?
